audio:
  power: 1
train:
  train_pickle: "data/small_combined_base.pkl"
  #train_pickle: "data/tiny.pkl"
  model_group: "scaled"
  model_type: "gernet"
  model_head: null
  model_size: 6.0
  out_channels: 256
  pretrained: False

  learning_rate: .0015
  pos_label_smoothing: 0.
  neg_label_smoothing: 0.

  fast_optimizer: true
  augment: false
  use_class_weights: false
  num_workers: 8
  shuffle: True

  num_epochs: 10
  save_last_n: 3
  multi_label: true
  num_folds: 1
  val_portion: 0
  seed: null
  deterministic: false
  prob_fade: 0 # .7 in HawkEars1
  min_fade: .1
  max_fade: 1.0

  # set data augmentations to match HawkEars1 defaults
  prob_simple_merge: 0.38
  augmentations:
  - name: add_real_noise
    prob: 0.32
    params:
      prob_fade: 0.2
      min_fade: 0.1
      max_fade: 0.8
  - name: add_white_noise
    prob: 0
    params:
      std: 0.05
  - name: freq_blur
    prob: 0
    params:
      sigma: 0.5
  - name: freq_mask
    prob: 0
    params:
      max_width: 8
  - name: shift_horizontal
    prob: 0.5
    params:
      max_shift: 8
  - name: speckle
    prob: 0
    params:
      variance: .012
  - name: time_mask
    prob: 0
    params:
      max_width: 8


