# Sample for training scaled GerNet, with recommended hyperparameters.
train:
  train_pickle: "data/small_combined_base.pkl"
  model_group: "scaled"
  model_type: "gernet"
  model_size: 6.0

  learning_rate: .002
  pos_label_smoothing: 0.08
  neg_label_smoothing: 0.01
  drop_rate: 0.0
  drop_path_rate: 0.0
  opt_weight_decay: 7e-5

  num_epochs: 10
  save_last_n: 3
  use_class_weights: false
  num_workers: 8
  seed: 100

  # tune augmentations (disable ones that aren't being tuned)
  augment: true
  prob_simple_merge: 0.3
  prob_fade1: 0.5
  min_fade1: 0.1
  max_fade1: 1.0

  augmentations:
  - name: add_real_noise
    prob: 0.3
    params:
      prob_fade2: 0.5
      min_fade2: 0.2
      max_fade2: 0.8
  - name: add_white_noise
    prob: 0.
    params:
      std1: 0.05
  - name: freq_blur
    prob: 0.
    params:
      sigma: 0.5
  - name: freq_mask
    prob: 0.
    params:
      max_width1: 8
  - name: shift_horizontal
    prob: 0.
    params:
      max_shift: 8
  - name: speckle
    prob: 0.
    params:
      std2: .1
  - name: time_mask
    prob: 0.
    params:
      max_width2: 8
